### ISSUE TITLE
Doesn't Work on iPhone

### ISSUE THREAD

**Issue by tpendragon** [osulp/CorvallisTour#21]
Seems to be a problem with safari.

**Comment by msg7086** [comment]
Tested with iPad and seems it works

**Comment by tpendragon** [comment]
> Tested with iPad and seems it works

Well, definitely doesn't work on two of the iPhones we tested. Looked kind of like a javascript error - the map window never initialized and it never asked for a location.

**Comment by msg7086** [comment]
```
Settings > Privacy > Location Services > Safari > Enable
```

That matters.

**Comment by tpendragon** [comment]
That's ridiculous. How is that not a default. Can you detect iPhones that fail and put up a message?

**Comment by msg7086** [comment]
![ct](https://f.cloud.github.com/assets/206155/2094001/7b7f687e-8ec3-11e3-8ea9-dedcc1ee71e7.png)

Weird line wraps. Any ideas?

**Comment by tpendragon** [comment]
No great ideas. I'm pretty okay with the wrapping, since it's an error message.
